mongodb:
    host: rokicki-ws
    port: 27017
    database: jos
    #username: flyportal
    #password: flyportal

scality:
    url: http://jacs-sproxyd:81/proxy
    driver: bparc2
  
httpClient:
    timeout: 30m
    connectionTimeout: 1s
    retries: 3
    userAgent: Janelia Object Store (JOS)
    
swagger:
    resourcePackage: org.janelia.jos
    title: Janelia Object Store API
    description: RESTful Microservice to the Janelia Object Store (JOS)
    contact: rokickik@janelia.hhmi.org

logging:
    level: INFO
    loggers:
        "org.janelia.jos": INFO
    
    